Repository traas-stack/holoinsight, pull requests merged in 2023-11, with the labels that each got.

#720 feat: agg fill zero
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/AggTask.java
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/AggTaskVersion.java
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/FillZero.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggTaskExecutor.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/PartitionProcessor.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/state/AggTaskState.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/state/AggWindowState.java
Labels: enhancement

#723 feat: add kafka producer healthchecker
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/kafka/KafkaProducerHealthChecker.java
  server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcher.java
Labels: enhancement

#730 feat: add ip and hostname in alert notification
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotify.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotifyRequest.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/DefaultAlertNotifyHandler.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertTemplateField.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotificationTemplate.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/TemplateValue.java
Labels: alert

#735 fix: alert silence
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
Labels: bug, alert

#737 fix: fix npe when building target
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/CollectTargetService.java
Labels: bug

#738 fix: alert return in advance
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/event/RecordSucOrFailNotify.java
Labels: bug, alert

#745 fix: get subscription for multiple alarm subscribers
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
Labels: bug, alert

#749 docs: update logo
  README-CN.md
  README.md
  docs/logo/HoloInsight LOGO-01.png
  docs/logo/HoloInsight LOGO-02.png
  docs/logo/HoloInsight LOGO-03.png
  docs/logo/HoloInsight LOGO-04.png
  docs/logo/HoloInsight LOGO-05.png
Labels: documentation

#748 feat: add details storage
  server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcher.java
  server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcherMockDataGenerator.java
  server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggGatewayHook.java
  server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbDetailsStorage.java
  server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/DetailsStorage.java
  server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/MetricMeterService.java
  server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/NoopDetailsStorage.java
  server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/Header.java
  server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/Row.java
  server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/Table.java
  server/gateway/gateway-boot/src/main/java/io/holoinsight/server/gateway/bootstrap/HoloinsightGatewayConfiguration.java
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/DetailsStorageService.java
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayGrpcServiceImpl.java
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHook.java
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/TaskResultUtils.java
Labels: enhancement

#751 feat: add gateway meta service
  server/gateway/gateway-core/pom.xml
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/GatewayMetaServiceImpl.java
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayGrpcServiceImpl.java
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHook.java
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHookManager.java
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayMetaService.java
Labels: enhancement
