Repository traas-stack/holoinsight, pull requests merged in 2023-03, with the labels that each got.

#166 docs: add product documentation links
  README.md
Labels: documentation

#174 fix: quick start demo use arm64v8 image in M1 mac
  deploy/examples/docker-compose/docker-compose.yaml
  deploy/examples/docker-compose/down.sh
  deploy/examples/docker-compose/up.sh
Labels: bug

#176 fix: use another way to fetch realpath
  deploy/examples/docker-compose/down.sh
  deploy/examples/docker-compose/up.sh
Labels: bug

#179 feat: supports building amd64/arm64v8 converged image
  .github/workflows/build-docker-image.yml
  scripts/docker/Dockerfile
  scripts/docker/buildx.sh
Labels: documentation

#182 feat: add github action workflow to build docker image
  .github/workflows/build-docker-image.yml
  scripts/all-in-one/build.sh
  scripts/docker/Dockerfile
  scripts/docker/buildx-one.sh
  scripts/docker/buildx.sh
Labels: enhancement

#181 fix: change http client
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlgorithmHttp.java
Labels: bug

#168 ci: add integration test basis using Github Actions
  .github/workflows/build.yml
  .github/workflows/integration-testing.yml
  deploy/examples/docker-compose/install-agent.sh
  deploy/examples/docker-compose/up.sh
Labels: enhancement

#187 docs: quick start demo requires docker-compose V2
  README-CN.md
  README.md
Labels: documentation

#188 refactor: Quick Start demo supports docker compose v1.29 && v2
  README-CN.md
  README.md
  deploy/examples/docker-compose/docker-compose.sh
  deploy/examples/docker-compose/docker-compose.yaml
  deploy/examples/docker-compose/down.sh
  deploy/examples/docker-compose/up.sh
Labels: refactor

#191 docs: update README
  README-CN.md
  README.md
Labels: documentation

#206 feat: optimize apm materialization
  server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/MetricsManager.java
  server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanMetricEsStorage.java
  server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/storage/MetricStorage.java
  server/apm/apm-server/apm-engine/src/main/resources/metrics/metrics-span.json
  server/apm/apm-server/apm-engine/src/main/resources/metrics/metrics.json
  server/apm/apm-server/apm-service/pom.xml
  server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/ApmMetricMaterializer.java
  server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/MetricServiceImpl.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictKey.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/common/MetaDictUtil.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/model/DataQueryRequest.java
  server/query/query-grpc-gen/src/main/java/io/holoinsight/server/query/grpc/QueryProto.java
  server/query/query-grpc-gen/src/main/proto/query_proto.proto
Labels: enhancement

#210 feat: improve duration parsing
  server/common/common/src/main/java/io/holoinsight/server/common/DurationUtil.java
  server/common/common/src/test/java/io/holoinsight/server/common/DurationUtilTest.java
  server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
  server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/QueryStorageUtils.java
Labels: enhancement

#214 build: use simple port healthcheck for better compatibility
  deploy/examples/docker-compose/docker-compose.yaml
  deploy/examples/k8s/overlays/example/wait-server.sh
Labels: enhancement

#215 docs: add links to holoinsight-docs website
  README-CN.md
  README.md
Labels: documentation

#231 fix: remove duplicated sql
  server/all-in-one/all-in-one-bootstrap/src/main/resources/db/migration/V1__230301_INIT_DDL.sql
  server/all-in-one/all-in-one-bootstrap/src/main/resources/db/migration/V2__230301_Uniform_COLUMN.sql
Labels: bug

#228 build: optimize example build
  deploy/examples/docker-compose/docker-compose.yaml
  deploy/examples/docker-compose/exec-sql-script.sh
  deploy/examples/docker-compose/init-db.sh
  scripts/docker/build.sh
  scripts/docker/buildx.sh
Labels: enhancement

#217 build(quick-start): get container name using docker inspect
  deploy/examples/docker-compose/.env
  deploy/examples/docker-compose/docker-compose.yaml
  deploy/examples/docker-compose/install-agent.sh
Labels: enhancement

#233 fix: fix example data.sql
  deploy/examples/docker-compose/data.sql
  deploy/examples/docker-compose/ddl.sql
Labels: bug

#246 fix: fix k8s demo db init error
  deploy/examples/k8s/overlays/example/init-db.sh
Labels: bug

#250 chore: remove extra quick start deployment files
  deploy/examples/docker-compose/.env-cn
  deploy/examples/docker-compose/docker-compose.yaml
  deploy/examples/docker-compose/down.sh
  deploy/examples/docker-compose/up.sh
  deploy/examples/k8s/overlays/example-cn/apply.sh
  deploy/examples/k8s/overlays/example-cn/kustomization.yaml
Labels: enhancement

#247 fix(extension-storage-ceresdbx): dont check ceresdb instance size
  server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxClientManager.java
Labels: bug

#253 ci: rename merge gate
  .github/workflows/merge-gate.yml
  scripts/add-license.sh
  scripts/check-format.sh
  scripts/check-license.sh
  scripts/format.sh
Labels: refactor

#257 fix: deleting the gaea collectconfig when deleting the logmonitor config
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/CustomPluginServiceImpl.java
Labels: bug

#259 test: optimize E2E test
  deploy/examples/docker-compose/data.sql
  deploy/examples/docker-compose/docker-compose.yaml
  deploy/examples/docker-compose/up.sh
  scripts/test/e2e/all.sh
  test/README-CN.md
  test/README.md
  test/scenes/common/base.yaml
  test/scenes/scene-default/data.sql
  test/scenes/scene-default/docker-compose.yaml
  test/scenes/scene-default/down.sh
  test/scenes/scene-default/up.sh
  test/server-e2e-test/pom.xml
  test/server-e2e-test/src/main/resources/junit-platform.properties
  test/server-e2e-test/src/test/java/extensions/io/restassured/response/ValidatableResponse/ValidatableResponseExtension.java
  test/server-e2e-test/src/test/java/extensions/io/restassured/specification/RequestSpecification/RequestSpecificationExtension.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/AgentVMIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/AppMonitoringIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/AuthIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/BaseIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/LogMonitoringFolderIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/LogMonitoringIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/MetaVMIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/ITSets.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/IntegrationBootstrapHelper.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/OneIntegrationBootstrapIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/SceneAndGroup.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/SceneDefaultIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/WarmupIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/env/DockerComposeEnv.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/env/Env.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/env/NoopEnv.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/utils/DockerHolder.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/utils/DockerUtils.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/utils/HackConditionEvaluationLogger.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/utils/TemporalDuration.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/utils/WebapiUtils.java
Labels: enhancement

#265 fix(home): fix alarm_rule workspace
  server/extension/extension-common-flyway/src/main/resources/db/migration/V3__230321_AlarmRule_COLUMN_workspace.sql
Labels: bug

#261 test: add second log monitoring E2E test
  scripts/docker/supervisord.conf
  test/scenes/scene-default/after.sh
  test/scenes/scene-default/log-generator.py
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/BaseIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/LogMonitoring_1_log_IT.java
  test/server-e2e-test/src/test/resources/requests/LogMonitoring_1_log_IT.json
Labels: test

#267 fix(home): fix alert history query condition
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmHistoryServiceImpl.java
Labels: bug

#277 feat(home): alarm hosting plugin
  .github/workflows/e2e-test.yml
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/AbstractHostingAlertPlugin.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/model/DefaultHostingAlertPlugin.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/model/HostingAlert.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/model/HostingAlertList.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationProductFacadeImpl.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/IntegrationPluginIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/ITSets.java
Labels: enhancement

#281 feat: optimize mappings between skywalking and opentelemetry
  server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/constants/Const.java
  server/apm/apm-common/src/main/java/io/holoinsight/server/apm/common/model/specification/OtlpMappings.java
Labels: enhancement

#282 test: optimize e2e result print
  .github/workflows/e2e-test.yml
  scripts/test/e2e/all.sh
  scripts/test/e2e/one.sh
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/RuleAlarmLoadData.java
  test/scenes/common/base.yaml
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/IntegrationBootstrapHelper.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/OneIntegrationBootstrapIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/bootstrap/SceneDefaultIT.java
  test/server-e2e-test/src/test/java/io/holoinsight/server/test/it/utils/MemoryTestExecutionListener.java
Labels: test

#284 feat: update ceresdb sdk
  deploy/examples/docker-compose/.env
  deploy/examples/docker-compose/ceresdb_entrypoint.sh
  deploy/examples/k8s/base/ceresdb.yaml
  server/extension/extension-storage-ceresdbx/pom.xml
  server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxClientManager.java
  server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java
  test/scenes/common/base.yaml
Labels: enhancement

#287 feat: add the metricTable key clean function
  server/common/common/src/main/java/io/holoinsight/server/common/LatchWork.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/model/DelTagReq.java
Labels: enhancement

#289 test: e2e test refactor
  test/scenes/common/agent.ini
  test/scenes/common/agent.yaml
  test/scenes/common/base.yaml
  test/scenes/common/exec-sql-script.sh
  test/scenes/common/init-db.sh
  test/scenes/common/log-alert-generator.py
  test/scenes/common/log-generator.py
  test/scenes/scene-default/after.sh
  test/scenes/scene-default/docker-compose.yaml
  test/server-e2e-test/pom.xml
  test/server-e2e-test/src/main/java/extensions/io/restassured/response/ValidatableResponse/ValidatableResponseExtension.java
  test/server-e2e-test/src/main/java/extensions/io/restassured/specification/RequestSpecification/RequestSpecificationExtension.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AgentVMIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertCalculateIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertDingDingRobotIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertRuleIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlertWebhookIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AppMonitoringIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AuthIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/BaseIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/DashboardIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/IntegrationPluginIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoringFolderIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoringIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoring_1_log_IT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/MetaVMIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/OpenMetricsScraperIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/ITSets.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/IntegrationBootstrapHelper.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/OneIntegrationBootstrapIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/SceneAndGroup.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/SceneDefaultIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/bootstrap/WarmupIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/env/DockerComposeEnv.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/env/Env.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/env/NoopEnv.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/utils/DockerHolder.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/utils/DockerUtils.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/utils/HackConditionEvaluationLogger.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/utils/MemoryTestExecutionListener.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/utils/TemporalDuration.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/utils/WebapiUtils.java
  test/server-e2e-test/src/main/resources/log4j2-test.xml
  test/server-e2e-test/src/main/resources/requests/AlertCalculateIT.json
  test/server-e2e-test/src/main/resources/requests/LogMonitoring_1_log_IT.json
Labels: test

#292 feat(home): Feeding time series data to anomaly algorithm
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/compute/algorithm/ExtendConfig.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/ValueDownAbnormalDetect.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/ValueUpAbnormalDetect.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/AIAlarmLoadData.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/trigger/RuleConfig.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/IntegrationPluginFacadeImpl.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/IntegrationPluginIT.java
Labels: enhancement

#296 fix(apm): fix some bugs
  server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/CommonBuilder.java
  server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/NetworkAddressMappingEsStorage.java
  server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/SpanMetricEsStorage.java
Labels: bug

#297 test: optimize e2e
  scripts/test/e2e/all.sh
  test/scenes/common/setup-env.sh
  test/scenes/scene-default/after.sh
  test/scenes/scene-default/docker-compose.yaml
  test/scenes/scene-default/down.sh
  test/scenes/scene-default/mysql-exec.sh
  test/scenes/scene-default/server-exec.sh
  test/scenes/scene-default/server-replace.sh
  test/scenes/scene-default/up.sh
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/env/DockerComposeEnv.java
Labels: test
