Repository traas-stack/holoinsight, pull requests merged in 2023-09, with the labels that each got.

#643 fix: fix sls meta
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/agent/AgentEventService.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsMetaSyncer.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/master/MasterService.java
Labels: bug

#648 feat: add workspace metricinfo map
  server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCache.java
  server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCacheService.java
  server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java
Labels: enhancement

#649 fix: query dashboard by type
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/DashboardFacadeImpl.java
Labels: enhancement, query

#651 feat: save pod silence events
  server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/elasticsearch/storage/impl/EventEsStorage.java
  server/apm/apm-server/apm-engine/src/main/java/io/holoinsight/server/apm/engine/storage/EventStorage.java
  server/apm/apm-server/apm-service/src/main/java/io/holoinsight/server/apm/server/service/impl/EventServiceImpl.java
  server/apm/apm-server/apm-web/src/main/java/io/holoinsight/server/apm/web/EventApi.java
  server/apm/apm-server/apm-web/src/main/java/io/holoinsight/server/apm/web/impl/EventApiController.java
  server/common/common-service/src/main/java/io/holoinsight/server/common/event/Event.java
  server/common/common-service/src/main/java/io/holoinsight/server/common/event/EventAutoConfiguration.java
  server/common/common-service/src/main/java/io/holoinsight/server/common/event/EventService.java
  server/common/common-service/src/main/java/io/holoinsight/server/common/event/NoopEventService.java
  server/common/common-service/src/main/resources/META-INF/spring.factories
  server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/TraceQueryFacadeImpl.java
  server/query/query-common/pom.xml
  server/query/query-common/src/main/java/io/holoinsight/server/query/common/convertor/ApmConvertor.java
  server/query/query-service/src/main/java/io/holoinsight/server/query/service/apm/ApmAPI.java
  server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/agent/AgentEventService.java
Labels: enhancement

#654 fix: remove sql in response
  server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java
  server/home/home-task/src/main/java/io/holoinsight/server/home/task/AbstractMetricCrawlerBuilder.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java
Labels: query

#659 feat: query MetricInfo by workspace
  server/home/home-boot/src/main/java/io/holoinsight/server/home/bootstrap/HoloinsightHomeConfiguration.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/MetricInfoCheckService.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/MetricInfoCheckServiceImpl.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetricInfoFacadeImpl.java
Labels: query

#664 feat: add gateway hook
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayGrpcServiceImpl.java
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHook.java
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHookManager.java
Labels: enhancement

#665 fix: alarm block
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
Labels: bug, alert

#668 fix: sql injection
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/MetricInfoCheckService.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/MetricInfoCheckServiceImpl.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/MetricInfoFacadeImpl.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
  server/home/home-web/src/test/java/io/holoinsight/server/home/web/controller/QueryFacadeImplTest.java
Labels: query

#669 fix: cluster task period
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/ClusterTaskServiceImpl.java
Labels: bug

#678 fix: check sql injection
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
Labels: query

#680 fix: add valid character
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/ParaCheckUtil.java
Labels: query

#682 feat: force set order config for alert compute
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/AlertClusterService.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/CoordinatorService.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/OrderConfig.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/coordinator/OrderMap.java
Labels: alert
