Repository traas-stack/holoinsight, pull requests merged in 2023-10, with the labels that each got.

#692 chore: add agg sql
  server/extension/extension-common-flyway/src/main/resources/db/migration/V22__231011_CREATE_agg_TABLE.sql
Labels: enhancement

#693 fix: fix kafka message size
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/GroupBy.java
  server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/executor/output/BatchSerdes.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/AggExecutorAutoConfiguration.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/AggExecutorConfig.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/ExecutorManager.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/XParserUtils.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/AsyncOutput.java
  server/extension/extension-common-flyway/src/main/resources/db/migration/V22__231011_CREATE_agg_TABLE.sql
Labels: bug

#697 feat: supports multi fields data aggregation and HLL operator
  server/agg/agg-boot/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggExecutorRegistryAutoConfiguration.java
  server/agg/agg-boot/src/main/java/io/holoinsight/server/agg/v1/executor/executor/MetricStorageOutput.java
  server/agg/agg-boot/src/main/java/io/holoinsight/server/agg/v1/executor/executor/RegistryInternalCompletenessService.java
  server/agg/agg-boot/src/main/resources/META-INF/spring.factories
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/AggFunc.java
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/CompletenessConfig.java
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/GroupBy.java
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/GroupByItem.java
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/data/AggTaskKey.java
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/data/DataAccessor.java
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/data/InDataNodeDataAccessor.java
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/data/TableRowDataAccessor.java
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/pb/AggProtos.java
  server/agg/agg-core/src/main/proto/agg.proto
  server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcher.java
  server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcherAutoConfiguration.java
  server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcherMockDataGenerator.java
  server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggGatewayHook.java
  server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/executor/executor/XWhere.java
  server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/pb/AggProtos.java
  server/agg/agg-executor-api/src/main/proto/agg.proto
  server/agg/agg-executor-bootstrap/src/main/java/io/holoinsight/server/agg/v1/executor/ExecutorMain.java
  server/agg/agg-executor/pom.xml
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/AggExecutorAutoConfiguration.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggTaskExecutor.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/BasicFieldAccessors.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/CompletenessUtils.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/Group.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/GroupField.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/HllState.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/RegistryHttpCompletenessService.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/TopnState.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/XParserUtils.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/XSelect.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/AsyncOutput.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/state/AggWindowState.java
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHook.java
  server/holoinsight-dependencies/pom.xml
Labels: enhancement

#699 refactor: refactor aggregation output
  server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcherAutoConfiguration.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/AggExecutorAutoConfiguration.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/Group.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/XSelect.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/AsyncOutput.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/XConsoleOutput.java
Labels: refactor

#700 fix: alert compute await
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/common/http/HttpProxy.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java
Labels: bug

#701 refactor: agg dispatcher
  server/agg/agg-boot/src/main/java/io/holoinsight/server/agg/v1/executor/executor/MetricStorageOutput.java
  server/agg/agg-boot/src/main/java/temp.groovy
  server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggDispatcher.java
  server/agg/agg-dispatcher/src/main/java/io/holoinsight/server/agg/v1/dispatcher/AggGatewayHook.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/XSelect.java
  server/gateway/gateway-core/src/main/java/io/holoinsight/server/gateway/core/grpc/GatewayHook.java
Labels: refactor

#702 fix: user check
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlarmGroupFacadeImpl.java
Labels: alert

#703 fix: agg output
  server/agg/agg-boot/src/main/java/io/holoinsight/server/agg/v1/executor/executor/MetricStorageOutput.java
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/AggProperties.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/AsyncOutput.java
Labels: bug

#707 refactor: agg window stat
  server/agg/agg-boot/src/main/java/io/holoinsight/server/agg/v1/executor/executor/MetricStorageOutput.java
  server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/executor/output/WindowStat.java
  server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/executor/output/XOutput.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggTaskExecutor.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/state/AggWindowState.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/state/StatePbConverter.java
Labels: refactor

#708 feat: agg topn
  server/agg/agg-core/src/main/java/io/holoinsight/server/agg/v1/core/conf/OutputItem.java
  server/agg/agg-executor/pom.xml
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/AggExecutorAutoConfiguration.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/AggTaskExecutor.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/XParserUtils.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/service/AggTaskV1Syncer.java
Labels: enhancement

#709 feat: alert pid
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertTemplateField.java
Labels: enhancement, alert

#712 feat: agg metric name format
  server/agg/agg-boot/src/main/java/io/holoinsight/server/agg/v1/executor/executor/MetricStorageOutput.java
  server/agg/agg-executor-api/pom.xml
  server/agg/agg-executor-api/src/main/java/io/holoinsight/server/agg/v1/executor/output/AggStringLookup.java
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/output/XConsoleOutput.java
  server/holoinsight-dependencies/pom.xml
Labels: enhancement

#717 fix: no exception in kafka rebalance listener
  server/agg/agg-executor/src/main/java/io/holoinsight/server/agg/v1/executor/executor/Executor.java
Labels: bug
