Repository traas-stack/holoinsight, pull requests merged in 2023-08, with the labels that each got.

#581 feat(home): add storage_tenant column in metric_info table
  server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/MetricInfo.java
  server/common/common-dao/src/main/java/io/holoinsight/server/common/dao/entity/dto/MetricInfoDTO.java
  server/extension/extension-common-flyway/src/main/resources/db/migration/V14__230801_ADD_metricinfo_COLUMN.sql
  server/home/home-task/src/main/java/io/holoinsight/server/home/task/AbstractMetricCrawlerBuilder.java
  server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/ApmMetricCrawlerBuilder.java
  server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/JvmMetricCrawlerBuilder.java
  server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/MysqlMetricCrawlerBuilder.java
  server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/PortCheckMetricCrawlerBuilder.java
  server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/SystemMetricCrawlerBuilder.java
Labels: enhancement

#584 refactor: openmetrics supports relabelconfigs
  server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/dto/OpenmetricsScraperDTO.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/OpenmetricsScraperUpdateListener.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/OpenmetricsScraperServiceImpl.java
  server/registry/registry-model/src/main/java/io/holoinsight/server/registry/model/OpenmetricsScraperTask.java
Labels: enhancement

#587 fix: setMetricRelabelConfigs
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/listener/OpenmetricsScraperUpdateListener.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/OpenmetricsScraperFacadeImpl.java
Labels: bug

#586 feat: track the processing of alerts
  server/common/common-service/src/main/java/io/holoinsight/server/common/service/FuseProtector.java
  server/common/common-service/src/test/java/io/holoinsight/server/common/service/FuseProtectorTest.java
  server/extension/extension-common-flyway/src/main/resources/db/migration/V15__230718_CREATE_alert_notify_record_TABLE.sql
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/compute/ComputeTaskPackage.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotify.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotifyRecordLatch.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/model/event/AlertNotifyRequest.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GatewayService.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GetSubscriptionHandler.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/NotifyChain.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AbstractUniformInspectRunningRule.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskCompute.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/converter/DoConvert.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/AlarmDataSet.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/event/RecordSucOrFailNotify.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/AlertTaskScheduler.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/task/CacheAlertTask.java
  server/home/home-alert/src/test/java/io/holoinsight/server/home/alert/service/calculate/AlertTaskComputeTest.java
  server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/converter/AlertNotifyRecordConverter.java
  server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/mapper/AlertNotifyRecordMapper.java
  server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlertNotifyRecord.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertNotifyRecordDTO.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlertRuleExtra.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/InspectConfig.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotifyErrorMsg.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotifyStage.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/NotifyUser.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/Steps.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/plugin/model/PluginContext.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/AlertNotifyRecordService.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlertNotifyRecordServiceImpl.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/AlertNotifyRecordController.java
Labels: enhancement, alert

#592 refactor: use es as default trace store in test scene
  scripts/docker/bin/health.sh
  test/scenes/common/base.yaml
  test/scenes/scene-default/application.yaml
  test/scenes/scene-default/docker-compose.yaml
Labels: refactor

#595 fix: alert extra npe
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/GatewayService.java
  server/home/home-task/src/main/java/io/holoinsight/server/home/task/crawler/PgMetricCrawlerBuilder.java
Labels: bug, alert

#597 fix: collect target type
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/grpc/RegistryServiceForAgentImpl.java
Labels: bug

#599 feat: ql query
  server/common/common-service/src/main/java/io/holoinsight/server/common/model/DataQueryRequest.java
  server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCache.java
  server/common/common-service/src/main/java/io/holoinsight/server/common/service/SuperCacheService.java
  server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
  server/home/home-web/src/test/java/io/holoinsight/server/home/web/controller/QueryFacadeImplTest.java
Labels: enhancement, query

#600 fix: log sample query
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/service/data/load/RuleAlarmLoadData.java
Labels: bug, alert

#606 feat: sql query
  server/extension/extension-storage-ceresdbx/src/main/java/io/holoinsight/server/extension/ceresdbx/CeresdbxMetricStorage.java
  server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/MetricStorage.java
  server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/NoopMetricStorage.java
  server/extension/extension-storage/src/main/java/io/holoinsight/server/extension/model/DetailResult.java
  server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/QueryClientService.java
  server/home/home-common/src/main/java/io/holoinsight/server/home/common/service/query/QueryDetailResponse.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
  server/home/home-web/src/test/java/io/holoinsight/server/home/web/controller/QueryFacadeImplTest.java
  server/query/query-grpc-gen/src/main/java/io/holoinsight/server/query/grpc/QueryProto.java
  server/query/query-grpc-gen/src/main/java/io/holoinsight/server/query/grpc/QueryServiceGrpc.java
  server/query/query-grpc-gen/src/main/proto/query_proto.proto
  server/query/query-server/src/main/java/io/holoinsight/server/query/server/rpc/QueryGrpcService.java
  server/query/query-service/src/main/java/io/holoinsight/server/query/service/QueryService.java
  server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Labels: query

#623 feat: add app column in alarm_history and alarm_history_detail
  server/extension/extension-common-flyway/src/main/resources/db/migration/V18__230822_ADD_alarm_history_COLUMN.sql
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertNotifyHandler.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/AlertSaveHistoryHandler.java
  server/home/home-alert/src/main/java/io/holoinsight/server/home/alert/plugin/DefaultAlertNotifyHandler.java
  server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/converter/AlarmHistoryConverter.java
  server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/converter/AlarmHistoryDetailConverter.java
  server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmHistory.java
  server/home/home-dal/src/main/java/io/holoinsight/server/home/dal/model/AlarmHistoryDetail.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmHistoryDTO.java
  server/home/home-facade/src/main/java/io/holoinsight/server/home/facade/AlarmHistoryDetailDTO.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmHistoryDetailServiceImpl.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/AlarmHistoryServiceImpl.java
Labels: alert

#624 feat: query schema by ql
  server/home/home-common/src/main/java/io/holoinsight/server/home/common/util/scope/MonitorCookieUtil.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/TenantInitService.java
  server/home/home-service/src/main/java/io/holoinsight/server/home/biz/service/impl/DefaultTenantInitServiceImpl.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/QueryFacadeImpl.java
  server/query/query-service/src/main/java/io/holoinsight/server/query/service/impl/DefaultQueryServiceImpl.java
Labels: enhancement, query

#626 feat: sync sls shard meta
  scripts/all-in-one/build.sh
  server/common/common/src/main/java/io/holoinsight/server/common/event/EventBusHolder.java
  server/common/common/src/main/java/io/holoinsight/server/common/event/ModuleInitEvent.java
  server/registry/registry-core/pom.xml
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/InitRunner.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/agent/AgentService.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/agent/AgentSyncer.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/CollectTargetService.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/TargetDebugService.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsConfig.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsDimConfiguration.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsLogstore.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsMetaSyncer.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/grpc/RegistryServiceForAgentImpl.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/template/ExecutorSelector.java
Labels: enhancement

#628 feat: query dashboard by type and title
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/common/DashboardType.java
  server/home/home-web/src/main/java/io/holoinsight/server/home/web/controller/DashboardFacadeImpl.java
Labels: query

#629 fix: fix filename of flyway dbconfig
  server/extension/extension-common-flyway/src/main/resources/db/migration/V19__230823_ADD_integration_plugin_COLUMN.sql
  server/extension/extension-common-flyway/src/main/resources/db/migration/V20__230828_ADD_metric_info_INDEX.sql
Labels: bug

#632 fix: fix IT
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AgentVMIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AlarmMetricFacadeIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/AppMonitoringIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/CeresdbPqlMonitoringIT.java
  test/server-e2e-test/src/main/java/io/holoinsight/server/test/it/LogMonitoringIT.java
  test/server-e2e-test/src/main/resources/requests/LogMonitoringIT.json
Labels: bug

#634 refactor: sls sync once
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsConfig.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/dim/SlsMetaSyncer.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/lock/LockService.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/master/MasterDemo.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/master/MasterJson.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/master/MasterListener.java
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/master/MasterService.java
Labels: refactor

#635 refactor: central agent
  server/registry/registry-core/src/main/java/io/holoinsight/server/registry/core/collecttarget/CollectTargetService.java
Labels: refactor
